# Generated by Django 4.2.2 on 2023-07-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cidade", "0001_initial"),
        ("curso", "0001_initial"),
        ("aluno", "0003_aluno_imagem_aluno_valor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cidade.cidade"
            ),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="curso.curso"
            ),
        ),
        migrations.DeleteModel(
            name="Cidade",
        ),
        migrations.DeleteModel(
            name="Curso",
        ),
    ]
