# Generated by Django 4.2.2 on 2023-07-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0004_alter_aluno_cidade_alter_aluno_curso_delete_cidade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="valor",
        ),
        migrations.AlterField(
            model_name="aluno",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="static/image"),
        ),
    ]
